### ISSUE TITLE
Homework4

### ISSUE THREAD

**Issue by JSDenis** [LordKorvin/homework4#1]
Кнопки лучше центрировать
![image](https://user-images.githubusercontent.com/32075762/67166536-13d85000-f399-11e9-8063-b757f4d4fb69.png)

**Comment by JSDenis** [comment]
На смартфонах нужно убрать это лишнее пространство. Сделай контейнер меньшей высоты.

**Comment by JSDenis** [comment]
![image](https://user-images.githubusercontent.com/32075762/67166559-4f731a00-f399-11e9-8bb0-74713c34021c.png)

**Comment by LordKorvin** [comment]
fixed
